### ISSUE TITLE
ejabberd staging deployment

### ISSUE THREAD

**Issue by tailic** [hausgold/docker-ejabberd#3]
Damit MVPF mit der Entwicklung gegen die XMPP API starten kann benötigen wir einen entsprechenden staging server.

**Comment by Jack12816** [comment]
@tailic Please setup a CNAME for `stage.jabber.hausgold.de` -> `jabber-stage-4e6fb84edbb7ac59.elb.eu-west-1.amazonaws.com`.

**Comment by Jack12816** [comment]
Credentials:
Username: `admin@stage.jabber.hausgold.de`
Password: `defaultpw`

**Comment by Jack12816** [comment]
We use the https://github.com/hausgold/docker-ejabberd Docker image right now. Just to fulfil the high-prio/MVPF requirements. The storage is wiped on every deployment, so it's not persistent right now. The Identity API external auth is also missing.

But they are good to go for their development from XMPP perspective.

**Comment by Jack12816** [comment]
Port mapping:
* 4560 (XMLRPC)
* 5222 (Client 2 Server)
* 5269 (Server 2 Server)
* 5280 (HTTP admin/websocket/http-bind) - this is also bound on tcp/80, just for the sake of http://stage.jabber.hausgold.de
* 5443 (HTTP Upload)

**Comment by tailic** [comment]
Superfast™ ;)
CNAME added
