### ISSUE TITLE
Messaging: ejabberd abschotten

### ISSUE THREAD

**Issue by marcusg** [hausgold/docker-ejabberd#5]
Vor production sollten wir uns die ejabberd.yml config nochmal genauer angucken und die Nutzung für fremde User verhindern. 

https://www.coverfire.com/archives/2009/10/17/ejabberd-default-permissions/ (alt, aber wer weiß ob sich da was geändert hat)

**Comment by tailic** [comment]
hausgold/docker-ejabberd#12
